admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
    
admin_caps_list:
    path: /kapsle/{page}
    defaults:
        page: 1
        _controller: AdminBundle:Caps:index
    requirements:
        page: \d+
        
admin_delete_cap:
    path: /kapsle/usun/{id}/{token}
    defaults:
        _controller: AdminBundle:Caps:delete
    requirements:
        id: \d+        

admin_cap_form_action:
    pattern: /kapsle/form/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AdminBundle:Caps:form 
        id: null            
       
admin_show_cap:
    pattern: /kapsle/pokaz/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AdminBundle:Caps:show 