admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
    
admin_caps_list:
    path: /kapsle/{page}
    defaults:
        page: 1
        _controller: AdminBundle:Caps:index
    requirements:
        page: \d+
        
admin_delete_cap:
    path: /kapsle/usun/{id}/{token}
    defaults:
        _controller: AdminBundle:Caps:delete
    requirements:
        id: \d+        

admin_cap_form_action:
    path: /kapsle/form/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AdminBundle:Caps:form 
        id: null            
       
admin_show_cap:
    path: /kapsle/pokaz/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AdminBundle:Caps:show 
        
admin_countries_list:
    path: /kraje/{page}
    defaults:
        page: 1
        _controller: AdminBundle:Countries:index
    requirements:
        page: \d+   
        
admin_show_country:
    path: /kraj/pokaz/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AdminBundle:Countries:show         
        
admin_delete_country:
    path: /kraj/usun/{id}/{token}
    defaults:
        _controller: AdminBundle:Countries:delete
    requirements:
        id: \d+        

admin_country_form_action:
    path: /kraj/form/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AdminBundle:Countries:form 
        id: null      
        
admin_breweries_list:
    path: /browar/{page}
    defaults:
        page: 1
        _controller: AdminBundle:Breweries:index
    requirements:
        page: \d+   
        
admin_show_brewery:
    path: /browar/pokaz/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AdminBundle:Breweries:show         
        
admin_delete_brewery:
    path: /browar/usun/{id}/{token}
    defaults:
        _controller: AdminBundle:Breweries:delete
    requirements:
        id: \d+        

admin_brewery_form_action:
    path: /browar/form/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AdminBundle:Breweries:form 
        id: null            

admin_cache_clear:
    path: /cache-clear
    defaults: 
        _controller: AdminBundle:Cache:clear
        
admin_cache:
    path: /cache
    defaults: 
        _controller: AdminBundle:Cache:index