services:
    admin.image_type_extension:
        class: AdminBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
    admin_bundle.twig.extension:
        class: AdminBundle\Twig\Extension\AdminExtension
        arguments: ["@doctrine", "@service_container", "@router"]
        tags:
            - { name : twig.extension }
    admin.image_path_validator:
        class: AdminBundle\Validator\Constraints\ImageFileValidator
        arguments: ["%kernel.root_dir%"]
        tags:
            - { name: validator.constraint_validator }
    admin.cap_image_handler:
        class: AdminBundle\Libs\CapImageHandler
        arguments: ["%kernel.root_dir%", "@doctrine"]
    admin.form.type.tagsinput:
        class: AdminBundle\Form\Type\TagsInputType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
