<?php

namespace AppBundle\Repository;

/**
 * FactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactsRepository extends \Doctrine\ORM\EntityRepository
{
}
