elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin-panel

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /


