app_homepage:
    path:     /{page}
    requirements:
        page: \d+
    defaults:
        _controller: AppBundle:Default:index
        page: 1 

caps_rss:
    path: /rss
    defaults:
        _controller: AppBundle:Feed:rss
        
caps_details:
    path: /kapsel/{slug}
    defaults:
        _controller: AppBundle:Caps:capsDetails
        
caps_search:
    path: /szukaj/{page}
    requirements:
        page: \d+
    defaults:
        _controller: AppBundle:Caps:search
        page: 1     
        
caps_ajax_autocomplete:
    path: /autocomplete
    defaults:
        _controller: AppBundle:Caps:autocomplete          
        
caps_login:
    path: /login
    defaults:
        _controller: AppBundle:Login:login

breweries_index:
    path: /browary/{page}
    requirements:
        page: \d+
    defaults:
        _controller: AppBundle:Breweries:index
        page: 1 

breweries_details:
    path: /browar/{slug}
    defaults:
        _controller: AppBundle:Breweries:details
        
contact:
    path: /kontakt
    defaults:
        _controller: AppBundle:Contact:index
    
_check_path:
    path: /login-check
    
_logout:
    path: /logout
    
subscribe:
    path: /subscribe
    defaults:
        _controller: AppBundle:Subscribe:subscribe