admin_homepage:
    path:     /
    defaults: { _controller: AppBundle:Backend/Default:index }
    
admin_caps_list:
    path: /caps/{page}
    defaults:
        page: 1
        _controller: AppBundle:Backend/Caps:index
    requirements:
        page: \d+
        
admin_delete_cap:
    path: /caps/delete/{id}
    defaults:
        _controller: AppBundle:Backend/Caps:delete
    requirements:
        id: \d+
    methods: DELETE

admin_edit_cap:
    path: /caps/edit/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:Backend/Caps:edit

admin_new_cap:
    path: /caps/new
    requirements:
    defaults:
        _controller: AppBundle:Backend/Caps:new
       
admin_show_cap:
    path: /kapsle/pokaz/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:Backend/Caps:show
        
admin_countries_list:
    path: /countries/{page}
    defaults:
        page: 1
        _controller: AppBundle:Backend/Countries:index
    requirements:
        page: \d+   
        
admin_show_country:
    path: /countries/show/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:Backend/Countries:show
        
admin_delete_country:
    path: /countries/delete/{id}
    defaults:
        _controller: AppBundle:Backend/Countries:delete
    requirements:
        id: \d+
    methods: DELETE

admin_edit_country:
    path: /countries/edit/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:Backend/Countries:edit

admin_new_country:
    path: /countries/new
    defaults:
        _controller: AppBundle:Backend/Countries:new
        
admin_breweries_list:
    path: /breweries/{page}
    defaults:
        page: 1
        _controller: AppBundle:Backend/Breweries:index
    requirements:
        page: \d+   
        
admin_show_brewery:
    path: /breweries/show/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:Backend/Breweries:show
        
admin_delete_brewery:
    path: /breweries/delete/{id}
    defaults:
        _controller: AppBundle:Backend/Breweries:delete
    requirements:
        id: \d+
    methods: DELETE

admin_new_brewery:
    path: /breweries/new
    defaults:
        _controller: AppBundle:Backend/Breweries:new

admin_edit_brewery:
    path: /breweries/edit/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:Backend/Breweries:edit

admin_pages_list:
    path: /pages/{page}
    defaults:
        page: 1
        _controller: AppBundle:Backend/Pages:index
    requirements:
        page: \d+

admin_show_page:
    path: /pages/show/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:Backend/Pages:show

admin_delete_page:
    path: /pages/delete/{id}
    defaults:
        _controller: AppBundle:Backend/Pages:delete
    requirements:
        id: \d+
    methods: DELETE

admin_new_page:
    path: /pages/new
    defaults:
        _controller: AppBundle:Backend/Pages:new

admin_edit_page:
    path: /pages/edit/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:Backend/Pages:edit
        id: null

admin_cache_clear:
    path: /cache-clear
    defaults: 
        _controller: AppBundle:Backend/Cache:clear
        
admin_cache:
    path: /cache
    defaults: 
        _controller: AppBundle:Backend/Cache:index

admin_users_list:
    path: /users/{page}
    defaults:
        page: 1
        _controller: AppBundle:Backend/Users:index
    requirements:
        page: \d+

admin_show_user:
    path: /users/show{id}
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:Backend/Users:show

admin_delete_user:
    path: /users/delete/{id}
    defaults:
        _controller: AppBundle:Backend/Users:delete
    requirements:
        id: \d+
    methods: DELETE

admin_edit_user:
    path: /users/edit/{id}
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:Backend/Users:edit

admin_new_user:
    path: /users/new
    requirements:
        id: \d+
    defaults:
        _controller: AppBundle:Backend/Users:new
        id: null

admin_my_account:
    path: /my-account
    defaults:
        _controller: AppBundle:Backend/Users:myAccount