services:
    app_bundle.twig.extension:
        class: AppBundle\Twig\Extension\AppExtension
        arguments: ["@doctrine", "@service_container", "@router"]
        tags:
            - { name : twig.extension }
    geocoder_cache:
        class: AppBundle\Utils\Services\Geocoder\Cache
        arguments: ["@service_container"]
    contact_mailer:
        class: AppBundle\Utils\Services\Mailer\ContactMailer
        arguments: ["@mailer", "%from_email%", "%from_name%", "%admin_email%"]
    app.login_listener:
        class: AppBundle\EventListener\LoginListener
        arguments: ['@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
    app.caps_paginator:
        class: AppBundle\Utils\Services\CapsPaginator
        arguments: ['@doctrine','@knp_paginator']
            