services:
    app_bundle.twig.extension:
        class: AppBundle\Twig\Extension\AppExtension
        arguments: ["@doctrine", "@service_container", @router]
        tags:
            - { name : twig.extension }